name: Pruebas Python

on:
  push:
    branches: [ main ]

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install pytest pytest-cov

    - name: Ejecutar pruebas
      run: pytest --cov=. --cov-fail-under=80
